
# Site settings
url: "https://tintinrevient.github.io"
baseurl: ""

# Build settings
markdown: kramdown

# Google tracking id
google-tracking-id: ""

# HTML Head
lang: "en"
author: "Zhao Shu"
sitename: "Zhao Shu"
title: "{ The Adventures of Tinin }"
favicon: "/assets/img/favicon.ico"

# Contact
email: "zhaobenben007@googlemail.com"

# Social Buttons
github: "tintinrevient"
instagram: "https://www.instagram.com/nezumikozo/"
linkedin: "https://www.linkedin.com/in/shu1zhao"

################################################################################

# Sections shown in the index page

# Reading Files
include:
   - _pages

pages_list:
  About: 'about'
  Projects: 'projects'
  Blog: 'latest-post'
  Publications: 'publications'
  Contact: 'contact'

# Exclusion list from the generated _site
exclude:
  - LICENSE
  - CONTRIBUTING
  - CONTRIBUTORS
  - src
  - node_modules
  - Gemfile
  - Rakefile
  - package.json
  - Gulpfile
  - website.todo
  - otherBlogs
  - gulp_examples
  - gulp

plugins:
  - jemoji
