
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://vcaldas.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: ""
# Build settings
markdown: kramdown

# Google tracking id
google-tracking-id: ""

#############
# HTML Head #
#############

lang: "en"
author: "Victor Caldas"
sitename: "Victor Caldas"
title: "{ V/Caldas }"
# description: "Blog and website of John Smith, blogging mainly for tech. Opinions expressed are mine."
# keywords: "smith, jones, personal, jekyll, theme"
favicon: "/img/favicon.ico"

##############################
# Dynamic Text on the Header #
##############################
#
# dynamic-typing: True
# shuffle: True # Shuffle the lines.
# loop: True
# loop-count: False # Set False for infinite loop, or set any number for finite loop.
# type-speed: 10
# start-delay: 200
# delete-delay: 5000
# lines: # You can add HTML Tags in the Text
#   - text: "The lower you fall, the higher you'll fly."
#   - text: "Where’s your will to be weird?"
#
# me-img: "/img/jetpacktocat.png"

##############################
# Color the browser elements #
##############################
# color-browser: "#000000"
# apple-status-bar-style: "black"


################
# Web app mode #
################

# web-app-mode: True

# Icons for Web App mode

# icon-36p: "/img/web-app/icon-36p.png"
# icon-48p: "/img/web-app/icon-48p.png"
# icon-72p: "/img/web-app/icon-72p.png"
# icon-96p: "/img/web-app/icon-96p.png"
# icon-144p: "/img/web-app/icon-144p.png"
# icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

# enable-gesture-navigation: True
#
# post-preview-words: 96
#
# paginate: 5
#
# email-share: True
# fb-share: True
# twitter-share: True
# linkedin-share: True
# reddit-share: True
# google-plus-share: True
# tumblr-share: True
# pinterest-share: True
# pocket-share: True
# vkontakte-share: True
#
# disqus-shortname: "panossakkos"
#
# syntax-highlight: True

############
# Timeline #
############

# events:
#   - image: "/img/timeline/spidertocat.png"
#     date: "September 2013 - Today"
#     description: "Saving the neighborhood!"
#   - image: "/img/timeline/baracktocat.jpg"
#     date: "September 2007 - August 2013"
#     description: "Started coding"

# First image of the Timeline

# timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "v.arminicaldas@vu.nl"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# # if the author_blurb is not set, then this feature is skipped
# author_blurb: "John Smith is an awesome person. He lives in Flatland, where he works on two-dimensional engineering projects. In his spare time, John likes to eat cotton candy."
# author_blurb_image: "/img/author.png"


# ##################
# # Social Buttons #
# ##################

twiter: "vcalds"
github: "vcaldas"
vimeo: "https://vimeo.com/vcaldas"
500px: "https://500px.com/victorcaldas"
linkedin: "https://www.linkedin.com/in/vcaldas/"
  # - title: "bitcoin"
  #   url: "https://blockchain.info/address/1LHuKC9Em3KA5yoZaf7nngnNdf9K7s2gSi"
  # - title: "rss"
  #   url: "/feed.xml"

############
# 404 page #
############

# err-404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

# keybase-username: johnsmith
# keybase-in-social: True
# keybase-in-footer: True

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

# Reading Files
include:
   - _pages

pages_list:
  About: 'about'
  Projects: 'projects'
  Blog: 'latest-post'
  Publications: 'publications'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude:
  - LICENSE
  - CONTRIBUTING
  - CONTRIBUTORS
  - src
  - node_modules
  - Gemfile
  - Rakefile
  - package.json
  - Gulpfile
  - website.todo
  - otherBlogs
  - gulp_examples
  - gulp



# Pagination path

# Build settings
# paginate: 5
# paginate_path: "/blog/page:num/"
# comments: true
# excerpt_separator: <!-- more -->


# paginate_path: "blog/page:num/"



plugins:
  # - jekyll-paginate
  - jemoji
